// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ADstat
double ADstat(NumericVector x);
RcppExport SEXP _lumen_ADstat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ADstat(x));
    return rcpp_result_gen;
END_RCPP
}
// ADtest
double ADtest(NumericVector x);
RcppExport SEXP _lumen_ADtest(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ADtest(x));
    return rcpp_result_gen;
END_RCPP
}
// ADprobExactInf
NumericVector ADprobExactInf(NumericVector a);
RcppExport SEXP _lumen_ADprobExactInf(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(ADprobExactInf(a));
    return rcpp_result_gen;
END_RCPP
}
// ADprobApproxInf
NumericVector ADprobApproxInf(NumericVector a);
RcppExport SEXP _lumen_ADprobApproxInf(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(ADprobApproxInf(a));
    return rcpp_result_gen;
END_RCPP
}
// ADprobN
NumericVector ADprobN(NumericVector a, int n);
RcppExport SEXP _lumen_ADprobN(SEXP aSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ADprobN(a, n));
    return rcpp_result_gen;
END_RCPP
}
// ADtestR
Rcpp::List ADtestR(const Rcpp::NumericVector& x);
RcppExport SEXP _lumen_ADtestR(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ADtestR(x));
    return rcpp_result_gen;
END_RCPP
}
// acceptBin
double acceptBin(int x, int n, double p);
RcppExport SEXP _lumen_acceptBin(SEXP xSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(acceptBin(x, n, p));
    return rcpp_result_gen;
END_RCPP
}
// bdci_exact_sas_rcpp
NumericVector bdci_exact_sas_rcpp(int x1, int n1, int x2, int n2, double alpha);
RcppExport SEXP _lumen_bdci_exact_sas_rcpp(SEXP x1SEXP, SEXP n1SEXP, SEXP x2SEXP, SEXP n2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(bdci_exact_sas_rcpp(x1, n1, x2, n2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// binomdiffciMee
double binomdiffciMee(int x1, int n1, int x2, int n2, double alpha, bool lower);
RcppExport SEXP _lumen_binomdiffciMee(SEXP x1SEXP, SEXP n1SEXP, SEXP x2SEXP, SEXP n2SEXP, SEXP alphaSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(binomdiffciMee(x1, n1, x2, n2, alpha, lower));
    return rcpp_result_gen;
END_RCPP
}
// binomdiffciMN
double binomdiffciMN(int x1, int n1, int x2, int n2, double z, bool lower);
RcppExport SEXP _lumen_binomdiffciMN(SEXP x1SEXP, SEXP n1SEXP, SEXP x2SEXP, SEXP n2SEXP, SEXP zSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(binomdiffciMN(x1, n1, x2, n2, z, lower));
    return rcpp_result_gen;
END_RCPP
}
// dgompertz_cpp
Rcpp::NumericVector dgompertz_cpp(const Rcpp::NumericVector& x, const Rcpp::NumericVector& shape, const Rcpp::NumericVector& rate, const bool log);
RcppExport SEXP _lumen_dgompertz_cpp(SEXP xSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dgompertz_cpp(x, shape, rate, log));
    return rcpp_result_gen;
END_RCPP
}
// pgompertz_cpp
Rcpp::NumericVector pgompertz_cpp(const Rcpp::NumericVector& q, const Rcpp::NumericVector& shape, const Rcpp::NumericVector& rate, const bool lower_tail, const bool give_log);
RcppExport SEXP _lumen_pgompertz_cpp(SEXP qSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP lower_tailSEXP, SEXP give_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type give_log(give_logSEXP);
    rcpp_result_gen = Rcpp::wrap(pgompertz_cpp(q, shape, rate, lower_tail, give_log));
    return rcpp_result_gen;
END_RCPP
}
// check_gompertz
Rcpp::LogicalVector check_gompertz(const Rcpp::NumericVector& shape, const Rcpp::NumericVector& rate);
RcppExport SEXP _lumen_check_gompertz(SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(check_gompertz(shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// jtpdf_cpp
NumericVector jtpdf_cpp(int mxsum, NumericVector cgsize, NumericVector pdf0, NumericVector pdf1);
RcppExport SEXP _lumen_jtpdf_cpp(SEXP mxsumSEXP, SEXP cgsizeSEXP, SEXP pdf0SEXP, SEXP pdf1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mxsum(mxsumSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cgsize(cgsizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pdf0(pdf0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pdf1(pdf1SEXP);
    rcpp_result_gen = Rcpp::wrap(jtpdf_cpp(mxsum, cgsize, pdf0, pdf1));
    return rcpp_result_gen;
END_RCPP
}
// pan
double pan(NumericVector A, int M, double C, int N);
RcppExport SEXP _lumen_pan(SEXP ASEXP, SEXP MSEXP, SEXP CSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(pan(A, M, C, N));
    return rcpp_result_gen;
END_RCPP
}
// pdirichlet_parallel_cpp
double pdirichlet_parallel_cpp(NumericVector q, NumericVector alpha, int n_sim);
RcppExport SEXP _lumen_pdirichlet_parallel_cpp(SEXP qSEXP, SEXP alphaSEXP, SEXP n_simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_sim(n_simSEXP);
    rcpp_result_gen = Rcpp::wrap(pdirichlet_parallel_cpp(q, alpha, n_sim));
    return rcpp_result_gen;
END_RCPP
}
// pruns_rcpp
double pruns_rcpp(int r, int n1, int n2, std::string alternative);
RcppExport SEXP _lumen_pruns_rcpp(SEXP rSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP alternativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    rcpp_result_gen = Rcpp::wrap(pruns_rcpp(r, n1, n2, alternative));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lumen_ADstat", (DL_FUNC) &_lumen_ADstat, 1},
    {"_lumen_ADtest", (DL_FUNC) &_lumen_ADtest, 1},
    {"_lumen_ADprobExactInf", (DL_FUNC) &_lumen_ADprobExactInf, 1},
    {"_lumen_ADprobApproxInf", (DL_FUNC) &_lumen_ADprobApproxInf, 1},
    {"_lumen_ADprobN", (DL_FUNC) &_lumen_ADprobN, 2},
    {"_lumen_ADtestR", (DL_FUNC) &_lumen_ADtestR, 1},
    {"_lumen_acceptBin", (DL_FUNC) &_lumen_acceptBin, 3},
    {"_lumen_bdci_exact_sas_rcpp", (DL_FUNC) &_lumen_bdci_exact_sas_rcpp, 5},
    {"_lumen_binomdiffciMee", (DL_FUNC) &_lumen_binomdiffciMee, 6},
    {"_lumen_binomdiffciMN", (DL_FUNC) &_lumen_binomdiffciMN, 6},
    {"_lumen_dgompertz_cpp", (DL_FUNC) &_lumen_dgompertz_cpp, 4},
    {"_lumen_pgompertz_cpp", (DL_FUNC) &_lumen_pgompertz_cpp, 5},
    {"_lumen_check_gompertz", (DL_FUNC) &_lumen_check_gompertz, 2},
    {"_lumen_jtpdf_cpp", (DL_FUNC) &_lumen_jtpdf_cpp, 4},
    {"_lumen_pan", (DL_FUNC) &_lumen_pan, 4},
    {"_lumen_pdirichlet_parallel_cpp", (DL_FUNC) &_lumen_pdirichlet_parallel_cpp, 3},
    {"_lumen_pruns_rcpp", (DL_FUNC) &_lumen_pruns_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_lumen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
