// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ad_stat_cpp
double ad_stat_cpp(NumericVector x);
RcppExport SEXP _lumen_ad_stat_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ad_stat_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// ad_test_cpp
double ad_test_cpp(NumericVector x);
RcppExport SEXP _lumen_ad_test_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ad_test_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// ad_prob_exact_inf_cpp
NumericVector ad_prob_exact_inf_cpp(NumericVector a);
RcppExport SEXP _lumen_ad_prob_exact_inf_cpp(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(ad_prob_exact_inf_cpp(a));
    return rcpp_result_gen;
END_RCPP
}
// ad_prob_approx_inf_cpp
NumericVector ad_prob_approx_inf_cpp(NumericVector a);
RcppExport SEXP _lumen_ad_prob_approx_inf_cpp(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(ad_prob_approx_inf_cpp(a));
    return rcpp_result_gen;
END_RCPP
}
// ad_prob_n_cpp
NumericVector ad_prob_n_cpp(NumericVector a, int n);
RcppExport SEXP _lumen_ad_prob_n_cpp(SEXP aSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ad_prob_n_cpp(a, n));
    return rcpp_result_gen;
END_RCPP
}
// ad_test_r_cpp
Rcpp::List ad_test_r_cpp(const Rcpp::NumericVector& x);
RcppExport SEXP _lumen_ad_test_r_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ad_test_r_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// binom_diff_ci_mee_cpp
double binom_diff_ci_mee_cpp(int x1, int n1, int x2, int n2, double alpha, bool lower);
RcppExport SEXP _lumen_binom_diff_ci_mee_cpp(SEXP x1SEXP, SEXP n1SEXP, SEXP x2SEXP, SEXP n2SEXP, SEXP alphaSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(binom_diff_ci_mee_cpp(x1, n1, x2, n2, alpha, lower));
    return rcpp_result_gen;
END_RCPP
}
// binom_diff_ci_mn_cpp
double binom_diff_ci_mn_cpp(int x1, int n1, int x2, int n2, double z, bool lower);
RcppExport SEXP _lumen_binom_diff_ci_mn_cpp(SEXP x1SEXP, SEXP n1SEXP, SEXP x2SEXP, SEXP n2SEXP, SEXP zSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(binom_diff_ci_mn_cpp(x1, n1, x2, n2, z, lower));
    return rcpp_result_gen;
END_RCPP
}
// blaker_find_crossing_cpp
double blaker_find_crossing_cpp(int x, int n, double alpha, double lo, double hi, bool from_left, double tol, int safe_steps);
RcppExport SEXP _lumen_blaker_find_crossing_cpp(SEXP xSEXP, SEXP nSEXP, SEXP alphaSEXP, SEXP loSEXP, SEXP hiSEXP, SEXP from_leftSEXP, SEXP tolSEXP, SEXP safe_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    Rcpp::traits::input_parameter< bool >::type from_left(from_leftSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type safe_steps(safe_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(blaker_find_crossing_cpp(x, n, alpha, lo, hi, from_left, tol, safe_steps));
    return rcpp_result_gen;
END_RCPP
}
// bm_core_cpp
NumericVector bm_core_cpp(NumericVector rx, NumericVector ry);
RcppExport SEXP _lumen_bm_core_cpp(SEXP rxSEXP, SEXP rySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rx(rxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ry(rySEXP);
    rcpp_result_gen = Rcpp::wrap(bm_core_cpp(rx, ry));
    return rcpp_result_gen;
END_RCPP
}
// bm_perm_exact_cpp
NumericVector bm_perm_exact_cpp(NumericVector rSorted, int n1, double tObs);
RcppExport SEXP _lumen_bm_perm_exact_cpp(SEXP rSortedSEXP, SEXP n1SEXP, SEXP tObsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rSorted(rSortedSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type tObs(tObsSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_perm_exact_cpp(rSorted, n1, tObs));
    return rcpp_result_gen;
END_RCPP
}
// bm_perm_mc_cpp
NumericVector bm_perm_mc_cpp(NumericVector rSorted, int n1, double tObs, int nPerm);
RcppExport SEXP _lumen_bm_perm_mc_cpp(SEXP rSortedSEXP, SEXP n1SEXP, SEXP tObsSEXP, SEXP nPermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rSorted(rSortedSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type tObs(tObsSEXP);
    Rcpp::traits::input_parameter< int >::type nPerm(nPermSEXP);
    rcpp_result_gen = Rcpp::wrap(bm_perm_mc_cpp(rSorted, n1, tObs, nPerm));
    return rcpp_result_gen;
END_RCPP
}
// dgompertz_cpp
Rcpp::NumericVector dgompertz_cpp(const Rcpp::NumericVector& x, const Rcpp::NumericVector& shape, const Rcpp::NumericVector& rate, const bool log);
RcppExport SEXP _lumen_dgompertz_cpp(SEXP xSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dgompertz_cpp(x, shape, rate, log));
    return rcpp_result_gen;
END_RCPP
}
// pgompertz_cpp
Rcpp::NumericVector pgompertz_cpp(const Rcpp::NumericVector& q, const Rcpp::NumericVector& shape, const Rcpp::NumericVector& rate, const bool lower_tail, const bool give_log);
RcppExport SEXP _lumen_pgompertz_cpp(SEXP qSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP lower_tailSEXP, SEXP give_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type give_log(give_logSEXP);
    rcpp_result_gen = Rcpp::wrap(pgompertz_cpp(q, shape, rate, lower_tail, give_log));
    return rcpp_result_gen;
END_RCPP
}
// check_gompertz_cpp
Rcpp::LogicalVector check_gompertz_cpp(const Rcpp::NumericVector& shape, const Rcpp::NumericVector& rate);
RcppExport SEXP _lumen_check_gompertz_cpp(SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(check_gompertz_cpp(shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// jtpdf_cpp
NumericVector jtpdf_cpp(IntegerVector gsize);
RcppExport SEXP _lumen_jtpdf_cpp(SEXP gsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type gsize(gsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(jtpdf_cpp(gsize));
    return rcpp_result_gen;
END_RCPP
}
// mad_boot_cpp
NumericVector mad_boot_cpp(NumericVector x, int R, double alpha, double constant, int seed, String method);
RcppExport SEXP _lumen_mad_boot_cpp(SEXP xSEXP, SEXP RSEXP, SEXP alphaSEXP, SEXP constantSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(mad_boot_cpp(x, R, alpha, constant, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// mad_diff_boot_cpp
NumericVector mad_diff_boot_cpp(NumericVector x, NumericVector y, int R, double alpha, double constant, int seed, String method);
RcppExport SEXP _lumen_mad_diff_boot_cpp(SEXP xSEXP, SEXP ySEXP, SEXP RSEXP, SEXP alphaSEXP, SEXP constantSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(mad_diff_boot_cpp(x, y, R, alpha, constant, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// mad_ratio_boot_cpp
NumericVector mad_ratio_boot_cpp(NumericVector x, NumericVector y, int R, double alpha, double constant, int seed, String method);
RcppExport SEXP _lumen_mad_ratio_boot_cpp(SEXP xSEXP, SEXP ySEXP, SEXP RSEXP, SEXP alphaSEXP, SEXP constantSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(mad_ratio_boot_cpp(x, y, R, alpha, constant, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// median_boot_cpp
NumericVector median_boot_cpp(NumericVector x, int R, double alpha, int seed, String method);
RcppExport SEXP _lumen_median_boot_cpp(SEXP xSEXP, SEXP RSEXP, SEXP alphaSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(median_boot_cpp(x, R, alpha, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// pan_cpp
double pan_cpp(NumericVector A, int M, double C, int N);
RcppExport SEXP _lumen_pan_cpp(SEXP ASEXP, SEXP MSEXP, SEXP CSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(pan_cpp(A, M, C, N));
    return rcpp_result_gen;
END_RCPP
}
// pdirichlet_cpp
double pdirichlet_cpp(NumericVector q, NumericVector alpha, int n_sim);
RcppExport SEXP _lumen_pdirichlet_cpp(SEXP qSEXP, SEXP alphaSEXP, SEXP n_simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_sim(n_simSEXP);
    rcpp_result_gen = Rcpp::wrap(pdirichlet_cpp(q, alpha, n_sim));
    return rcpp_result_gen;
END_RCPP
}
// pruns_cpp
double pruns_cpp(int r, int n1, int n2, std::string alternative);
RcppExport SEXP _lumen_pruns_cpp(SEXP rSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP alternativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    rcpp_result_gen = Rcpp::wrap(pruns_cpp(r, n1, n2, alternative));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lumen_ad_stat_cpp", (DL_FUNC) &_lumen_ad_stat_cpp, 1},
    {"_lumen_ad_test_cpp", (DL_FUNC) &_lumen_ad_test_cpp, 1},
    {"_lumen_ad_prob_exact_inf_cpp", (DL_FUNC) &_lumen_ad_prob_exact_inf_cpp, 1},
    {"_lumen_ad_prob_approx_inf_cpp", (DL_FUNC) &_lumen_ad_prob_approx_inf_cpp, 1},
    {"_lumen_ad_prob_n_cpp", (DL_FUNC) &_lumen_ad_prob_n_cpp, 2},
    {"_lumen_ad_test_r_cpp", (DL_FUNC) &_lumen_ad_test_r_cpp, 1},
    {"_lumen_binom_diff_ci_mee_cpp", (DL_FUNC) &_lumen_binom_diff_ci_mee_cpp, 6},
    {"_lumen_binom_diff_ci_mn_cpp", (DL_FUNC) &_lumen_binom_diff_ci_mn_cpp, 6},
    {"_lumen_blaker_find_crossing_cpp", (DL_FUNC) &_lumen_blaker_find_crossing_cpp, 8},
    {"_lumen_bm_core_cpp", (DL_FUNC) &_lumen_bm_core_cpp, 2},
    {"_lumen_bm_perm_exact_cpp", (DL_FUNC) &_lumen_bm_perm_exact_cpp, 3},
    {"_lumen_bm_perm_mc_cpp", (DL_FUNC) &_lumen_bm_perm_mc_cpp, 4},
    {"_lumen_dgompertz_cpp", (DL_FUNC) &_lumen_dgompertz_cpp, 4},
    {"_lumen_pgompertz_cpp", (DL_FUNC) &_lumen_pgompertz_cpp, 5},
    {"_lumen_check_gompertz_cpp", (DL_FUNC) &_lumen_check_gompertz_cpp, 2},
    {"_lumen_jtpdf_cpp", (DL_FUNC) &_lumen_jtpdf_cpp, 1},
    {"_lumen_mad_boot_cpp", (DL_FUNC) &_lumen_mad_boot_cpp, 6},
    {"_lumen_mad_diff_boot_cpp", (DL_FUNC) &_lumen_mad_diff_boot_cpp, 7},
    {"_lumen_mad_ratio_boot_cpp", (DL_FUNC) &_lumen_mad_ratio_boot_cpp, 7},
    {"_lumen_median_boot_cpp", (DL_FUNC) &_lumen_median_boot_cpp, 5},
    {"_lumen_pan_cpp", (DL_FUNC) &_lumen_pan_cpp, 4},
    {"_lumen_pdirichlet_cpp", (DL_FUNC) &_lumen_pdirichlet_cpp, 3},
    {"_lumen_pruns_cpp", (DL_FUNC) &_lumen_pruns_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_lumen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
