# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ad_stat_cpp <- function(x) {
    .Call(`_lumen_ad_stat_cpp`, x)
}

ad_test_cpp <- function(x) {
    .Call(`_lumen_ad_test_cpp`, x)
}

ad_prob_exact_inf_cpp <- function(a) {
    .Call(`_lumen_ad_prob_exact_inf_cpp`, a)
}

ad_prob_approx_inf_cpp <- function(a) {
    .Call(`_lumen_ad_prob_approx_inf_cpp`, a)
}

ad_prob_n_cpp <- function(a, n) {
    .Call(`_lumen_ad_prob_n_cpp`, a, n)
}

ad_test_r_cpp <- function(x) {
    .Call(`_lumen_ad_test_r_cpp`, x)
}

binom_diff_ci_mee_cpp <- function(x1, n1, x2, n2, alpha, lower) {
    .Call(`_lumen_binom_diff_ci_mee_cpp`, x1, n1, x2, n2, alpha, lower)
}

binom_diff_ci_mn_cpp <- function(x1, n1, x2, n2, z, lower) {
    .Call(`_lumen_binom_diff_ci_mn_cpp`, x1, n1, x2, n2, z, lower)
}

blaker_find_crossing_cpp <- function(x, n, alpha, lo, hi, from_left, tol = 1e-12, safe_steps = 2000L) {
    .Call(`_lumen_blaker_find_crossing_cpp`, x, n, alpha, lo, hi, from_left, tol, safe_steps)
}

#' @noRd
bm_core_cpp <- function(rx, ry) {
    .Call(`_lumen_bm_core_cpp`, rx, ry)
}

#' @noRd
bm_perm_exact_cpp <- function(rSorted, n1, tObs) {
    .Call(`_lumen_bm_perm_exact_cpp`, rSorted, n1, tObs)
}

#' @noRd
bm_perm_mc_cpp <- function(rSorted, n1, tObs, nPerm) {
    .Call(`_lumen_bm_perm_mc_cpp`, rSorted, n1, tObs, nPerm)
}

dgompertz_cpp <- function(x, shape, rate, log) {
    .Call(`_lumen_dgompertz_cpp`, x, shape, rate, log)
}

pgompertz_cpp <- function(q, shape, rate, lower_tail, give_log) {
    .Call(`_lumen_pgompertz_cpp`, q, shape, rate, lower_tail, give_log)
}

check.gompertz <- function(shape, rate) {
    .Call(`_lumen_check_gompertz_cpp`, shape, rate)
}

jtpdf_cpp <- function(gsize) {
    .Call(`_lumen_jtpdf_cpp`, gsize)
}

mad_boot_cpp <- function(x, R = 1000L, alpha = 0.05, constant = 1.4826, seed = -1L, method = "perc") {
    .Call(`_lumen_mad_boot_cpp`, x, R, alpha, constant, seed, method)
}

mad_diff_boot_cpp <- function(x, y, R = 1000L, alpha = 0.05, constant = 1.4826, seed = -1L, method = "perc") {
    .Call(`_lumen_mad_diff_boot_cpp`, x, y, R, alpha, constant, seed, method)
}

mad_ratio_boot_cpp <- function(x, y, R = 1000L, alpha = 0.05, constant = 1.4826, seed = -1L, method = "perc") {
    .Call(`_lumen_mad_ratio_boot_cpp`, x, y, R, alpha, constant, seed, method)
}

median_boot_cpp <- function(x, R = 1000L, alpha = 0.05, seed = -1L, method = "perc") {
    .Call(`_lumen_median_boot_cpp`, x, R, alpha, seed, method)
}

pan_cpp <- function(A, M, C, N) {
    .Call(`_lumen_pan_cpp`, A, M, C, N)
}

pdirichlet_cpp <- function(q, alpha, n_sim) {
    .Call(`_lumen_pdirichlet_cpp`, q, alpha, n_sim)
}

pruns_cpp <- function(r, n1, n2, alternative = "two.sided") {
    .Call(`_lumen_pruns_cpp`, r, n1, n2, alternative)
}

