# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADstat <- function(x) {
    .Call(`_lumen_ADstat`, x)
}

ADtest <- function(x) {
    .Call(`_lumen_ADtest`, x)
}

ADprobExactInf <- function(a) {
    .Call(`_lumen_ADprobExactInf`, a)
}

ADprobApproxInf <- function(a) {
    .Call(`_lumen_ADprobApproxInf`, a)
}

ADprobN <- function(a, n) {
    .Call(`_lumen_ADprobN`, a, n)
}

ADtestR <- function(x) {
    .Call(`_lumen_ADtestR`, x)
}

acceptBin <- function(x, n, p) {
    .Call(`_lumen_acceptBin`, x, n, p)
}

binomdiffciMee <- function(x1, n1, x2, n2, alpha, lower) {
    .Call(`_lumen_binomdiffciMee`, x1, n1, x2, n2, alpha, lower)
}

binomdiffciMN <- function(x1, n1, x2, n2, z, lower) {
    .Call(`_lumen_binomdiffciMN`, x1, n1, x2, n2, z, lower)
}

coef_boot_cpp <- function(X, y, B = 2000L, alpha = 0.05, seed = -1L) {
    .Call(`_lumen_coef_boot_cpp`, X, y, B, alpha, seed)
}

dgompertz_cpp <- function(x, shape, rate, log) {
    .Call(`_lumen_dgompertz_cpp`, x, shape, rate, log)
}

pgompertz_cpp <- function(q, shape, rate, lower_tail, give_log) {
    .Call(`_lumen_pgompertz_cpp`, q, shape, rate, lower_tail, give_log)
}

check.gompertz <- function(shape, rate) {
    .Call(`_lumen_check_gompertz`, shape, rate)
}

jtpdf_cpp <- function(mxsum, cgsize, pdf0, pdf1) {
    .Call(`_lumen_jtpdf_cpp`, mxsum, cgsize, pdf0, pdf1)
}

pan <- function(A, M, C, N) {
    .Call(`_lumen_pan`, A, M, C, N)
}

pdirichlet_cpp <- function(q, alpha, n_sim) {
    .Call(`_lumen_pdirichlet_cpp`, q, alpha, n_sim)
}

rsq_boot_cpp <- function(X, y, B = 1000L, alpha = 0.05, adjusted = TRUE, seed = -1L) {
    .Call(`_lumen_rsq_boot_cpp`, X, y, B, alpha, adjusted, seed)
}

pruns_rcpp <- function(r, n1, n2, alternative = "two.sided") {
    .Call(`_lumen_pruns_rcpp`, r, n1, n2, alternative)
}

