# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADstat <- function(x) {
    .Call(`_DescToolsTests_ADstat`, x)
}

ADtest <- function(x) {
    .Call(`_DescToolsTests_ADtest`, x)
}

ADprobExactInf <- function(a) {
    .Call(`_DescToolsTests_ADprobExactInf`, a)
}

ADprobApproxInf <- function(a) {
    .Call(`_DescToolsTests_ADprobApproxInf`, a)
}

ADprobN <- function(a, n) {
    .Call(`_DescToolsTests_ADprobN`, a, n)
}

ADtestR <- function(x) {
    .Call(`_DescToolsTests_ADtestR`, x)
}

jtpdf_cpp <- function(mxsum, cgsize, pdf0, pdf1) {
    .Call(`_DescToolsTests_jtpdf_cpp`, mxsum, cgsize, pdf0, pdf1)
}

pan <- function(A, M, C, N) {
    .Call(`_DescToolsTests_pan`, A, M, C, N)
}

pruns_rcpp <- function(r, n1, n2, alternative = "two.sided") {
    .Call(`_DescToolsTests_pruns_rcpp`, r, n1, n2, alternative)
}

